runtime: python310
entrypoint: gunicorn --timeout=30 --bind 0.0.0.0:$PORT main:app



env_variables:
    MONGODB_URI: mongodb+srv://pwsdelta_user:asdfghjkl@cluster0.8uviyvr.mongodb.net/mtgdbmongo?retryWrites=true&w=majority&appName=Cluster0


