runtime: python310  # Or your Python version (3.7, 3.8, etc.)
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /.*
  script: auto

# Health check configuration
health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

env_variables:
    MONGODB_URI: mongodb+srv://pwsdelta_user:asdfghjkl@cluster0.8uviyvr.mongodb.net/mtgdbmongo?retryWrites=true&w=majority&appName=Cluster0


