runtime: python310
entrypoint: gunicorn --timeout=60 --bind :$PORT main:app


env_variables:
    MONGODB_URI: mongodb+srv://pwsdelta_user:asdfghjkl@cluster0.8uviyvr.mongodb.net/mtgdbmongo?retryWrites=true&w=majority&appName=Cluster0


